import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import "./styles.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <div className="wrap">
          <Header />
          <div className="container">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
